apiVersion: v1
kind: ConfigMap
metadata:
  name: unleash-config
data:
  DATABASE_HOST: unleash.cmmq2liqtqbg.eu-west-3.rds.amazonaws.com
  DATABASE_NAME: unleash
  DATABASE_USERNAME: unleash_user
  DATABASE_SSL: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unleash
  name: unleash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unleash
  template:
    metadata:
      labels:
        app: unleash
    spec:
      containers:
      - image: unleashorg/unleash-server
        name: unleash-server
        ports:
        - containerPort: 4242
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: unleashpassw
              key: DATABASE_PASSWORD                    
        envFrom:
        - configMapRef:
            name: unleash-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unleash
  name: unleash-svc
spec:
  ports:
  - port: 4242
    protocol: TCP
    targetPort: 4242
  selector:
    app: unleash
  type: NodePort
